### ISSUE TITLE
request to allow user to set ABT_THREAD_STACKSIZE via environment variable

### ISSUE THREAD

**Issue by adammoody** [mochi-hpc/mochi-margo#152]
In UnifyFS, we recently ran into a thread stack size problem, because we had been calling ``ABT_init`` before ``margo_init``.  After realizing that, we decided to drop our call to ``ABT_init`` and just defer to margo to do that for us.

In the process of debugging, I came across ``margo_set_abt_thread_stacksize`` which allows a user to set the thread stack size through a margo API call.  It looks to me like margo itself calls this function to set the stack size to 2MB by default unless the user has specified something different in a margo config file.

I am also wondering if it would be possible to let the user to set the stack size through their environment.

It looks like the line below will *replace* any setting the user might have set.

https://github.com/mochi-hpc/mochi-margo/blob/9bc7b844ecb9c2a1bf4b044716100c3bd949e8dc/src/margo-util.c#L34

Could that be changed to not overwrite the user's setting?

That is, change the above to:
```
setenv("ABT_THREAD_STACKSIZE", env_str, 0); 
```

**Comment by mdorier** [comment]
I'll let @carns decide what's best, but just a couple of comments:
- `margo_set_abt_thread_stacksize` should still be called before Argobots and/or Margo are initialized (it's just a convenience function to set the environment variable).
- The logic of checking whether `ABT_THREAD_STACKSIZE` was defined by the user before changing it can easily be implemented by service developers by checking for the presence of this variable before calling `margo_set_abt_thread_stacksize`.
- That said, our logic in `margo_init_ext` was to make `ABT_THREAD_STACKSIZE` have precedence over any thread stack size defined in the JSON configuration, so maybe `margo_set_abt_thread_stacksize` should also leave any `ABT_THREAD_STACKSIZE` untouched if already defined.

**Comment by carns** [comment]
Timely question @adammoody since https://github.com/mochi-hpc/mochi-margo/releases/tag/v0.9.5 just came out a few days ago :)

This release actually has two relevant changes:

- There is a new user-facing API function called `margo_set_environment()` that can be called prior to `ABT_init()` if you would like to call `ABT_init()` directly before starting Margo.  It will set the same Argobots configuration parameters (thread stack size, in particular) that `margo_init_ext()` would have.  We made this an API function for safety in case defaults change or we find other runtime parameters that need to be set prior to Argobots initialization().  If you are using a custom value for the stacksize via json parameters, then the `margo_set_environment()` function will accept the same json as an argument so that it will be consistent.  
- Regardless of the above, the Margo init functions now all perform runtime checks to see if things like the stacksize match what it expects.  If not, then it will emit a verbose warning message (see https://github.com/mochi-hpc/mochi-margo/blob/v0.9.5/src/margo-init.c#L1497)

Does that sound like it will accomplish what you want?

**Comment by carns** [comment]
We realized this morning that the 0.9.5 release (features described above) isn't available in Spack upstream yet.  I just opened a PR for it https://github.com/spack/spack/pull/25365.

It's already available in the external mochi spack repository: https://github.com/mochi-hpc/mochi-spack-packages

**Comment by adammoody** [comment]
Thanks @mdorier and @carns .  I suspect that should be good for us if we go back to calling ``ABT_init`` directly, though we probably will be content by deferring to margo to do it for us.  It's good to know this is an option in case we go back to calling ``ABT_init`` directly.

My question about not overwriting the environment variable comes more from the idea of helping a user work around a problem where perhaps even the margo stack size of 2MB is too small.  This is likely rare, but if it does show up, an easy work around would be to ask the user to set ``export ABT_THREAD_STACKSIZE=4MB``.  Having said that, this is likely rare enough to not worry about it, and they could do it through a config file instead.

**Comment by carns** [comment]
Ah, I see.  Yeah, I think if possible the best way with the most recent Margo releases would be to use a json string like this:

```
{ "argobots":{ "abt_thread_stacksize":4194304 } }
```
(escape the double quotes like \" if you want to inject this programmatically from C).  Then pass that same string to both `margo_set_environment()` (only necessary if `ABT_Init()` is called externally) and `margo_init_ext()`, to make sure it is consistent.

**Comment by carns** [comment]
Also a quick tip if you want to test out json parameters like that: there is a test program called `tests/margo-test-init-ext` in the source tree that will take a json file as an argument.  It then just starts up and shuts down margo, dumping the resulting fully resolved json on the way out.

You can use that as a quick sanity check for programmatic json string changes (to make sure they parse clean and take effect as expected in the fully resolved runtime json).
