### ISSUE TITLE
libtool:   error: only absolute run-paths are allowed

### ISSUE THREAD

**Issue by bnicolae** [mochi-hpc/mochi-margo#226]
This is happening because an extra empty "-R" is passed to libtool. It's easy manual fix (remove the extra -R from libtool parameters in the generated Makefile) but still worth noting.

**Comment by carns** [comment]
Thanks @bnicolae .  I think this was fixed by https://github.com/mochi-hpc/mochi-margo/pull/224 , but we haven't tagged a release yet.  We will soon after confirming some other fixes.  In the mean time you should be able to work around this as well by building mochi-margo@main (or origin/main out of git).
