### ISSUE TITLE
Cannot build the latest main branch with json-c-0.11

### ISSUE THREAD

**Issue by Zhang690683220** [mochi-hpc/mochi-margo#239]
Hi,

I think there are still some issues in building with old json-c as #234 . This time json-c 0.11 doesn't work.

**Comment by mdorier** [comment]
Hi @Zhang690683220,

Is working with with such an old version of json-c really a requirement for you?

I did a couple of commits that defined some missing macros, but then hit a linking error because a handful of json-c functions that we use do not exist in json-c 0.11. I could go ahead and copy their implementation from the json-c repo, but I don't think their place is in margo in the first place. I am more tempted to specify in the margo package that it requires at least json-c 0.13.

**Comment by Zhang690683220** [comment]
Hi @mdorier,

Actually, I'm working on Frontera where they only have a json-c-0.11 in `/usr/include/json-c` . It's even worse than having nothing at that place because more or less some code will locate the header file there and report some missing definitions. I'm asking them to update the json-c. But is there any other workaround I can do to get margo working with the json-c I installed elsewhere?

**Comment by mdorier** [comment]
I'm asking because when I do `make -n` on Margo to see what gcc commands are run, `/usr/include` is not specified explicitly, the path to the spack-installed json-c is, and according to what I can read on documentation, gcc should be preferring whatever is explicitly specified, over a system path. If a system path is polluting a build, it's more problematic than just making sure the code works with what the system provides. Ideally a system path should NOT pollute the build.

**Comment by Zhang690683220** [comment]
No. I don't use spack at all. I just built my libfabric, mercury, argobots, json-c then export these `LD_LIBRARY_PATH` and `PKG_CONFIG_PATH`. So is there any way that I can prioritize my json-c path in gcc?

**Comment by mdorier** [comment]
Normally margo should already prioritize your own json-c if `PKG_CONFIG_PATH` is set correctly. Can you do `pkg-config --cflags json-c` and give me the output?

Can you do `make -n` (after configure) on margo and report the first gcc call you see? It should look something like this:

```
gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I/projects/spack/opt/spack/linux-ubuntu22.04-sandybridge/gcc-11.3.0/json-c-0.13.1-qa5mcv5q5isal3o5u75fpv4zhehxfe5h/include -I/projects/spack/opt/spack/linux-ubuntu22.04-sandybridge/gcc-11.3.0/argobots-1.1-b4vexr5bgzhh2pa6ithfkasj3r7fzai3/include -I/projects/spack/opt/spack/linux-ubuntu22.04-sandybridge/gcc-11.3.0/mercury-2.2.0-swa45t5ia6ymx7tjwxgo5o7nqmbzgemg/include   -Wno-address -I/projects/spack/opt/spack/linux-ubuntu22.04-sandybridge/gcc-11.3.0/json-c-0.13.1-qa5mcv5q5isal3o5u75fpv4zhehxfe5h/include -DMARGO_USE_JSON_C -I/projects/spack/opt/spack/linux-ubuntu22.04-sandybridge/gcc-11.3.0/argobots-1.1-b4vexr5bgzhh2pa6ithfkasj3r7fzai3/include -I/projects/spack/opt/spack/linux-ubuntu22.04-sandybridge/gcc-11.3.0/mercury-2.2.0-swa45t5ia6ymx7tjwxgo5o7nqmbzgemg/include -g -O2 -pthread -MT src/margo-info.o -MD -MP -MF $depbase.Tpo -c -o src/margo-info.o ../src/margo-info.c &&\
```

**Comment by Zhang690683220** [comment]
Oh. I made it work now. I think the reason is that somehow they named some of the `lib` dir to be `lib64`. But big thanks anyway!
